import { request } from "http";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import Results from "../components/Results";
import requests from "../utils/requests";

const Home: NextPage = ({ results }) => {
  //console.log(props);

  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NavBar />
      <Results results={results} />
    </div>
  );
};

export default Home;

export async function getServerSideProps(context) {
  const genere = context.query.genre;
  const url = `https://api.themoviedb.org/3${
    requests[genere]?.url || requests.fetchTrending.url
  }`;
  console.log(url);
  const request = await fetch(url).then((res) => res.json());
  //.then((res) => console.log("re", res))
  //.catch((err) => console.log("err", err));
  return {
    props: {
      results: request?.results ?? null,
    },
  };
}
